package:
  name: generator
  version: "0.2.0"

source:
  path: ../

extra:
  channels:
    - potassco
    - asprilo

requirements:
  build:
    - clingo
    - python>=3
    - pyyaml>=3.12
    - setuptools
  run:
    - clingo
    - python>=3
    - pyyaml>=3.12

test:
  imports:
    - generator

build:
  entry_points:
    - gen = generator.__main__:main

about:
  home: https://github.com/potassco/asprilo/tree/develop/generator
  summary: "The Asprilo Instance Generator - https://potassco.org/asprilo"
